clear_output: true
force_cpu: false
max_threads: 3
memory_limit: 0
output_image_format: jpg
output_show_video: true
output_template: '{file}_{time}'
output_video_codec: libx264
output_video_format: mp4
provider: cuda
selected_theme: Default
server_name: ''
server_port: 0
server_share: false
use_os_temp_folder: false
video_quality: 14
