clear_output: true
fal_token: ''
force_cpu: false
huggingface_token: ''
last_source_folder: D:\.autodeep_temp\0fdfb2d1523f068c8635956f82bb3df84022435287569ced07029975d5c85cbb
last_target_folder: C:\Users\INdaHouse\Desktop\AutoDeep_Destino
max_threads: 4
memory_limit: 0
output_image_format: png
output_path: ''
output_show_video: true
output_template: '{file}_{time}'
output_video_codec: libx264
output_video_format: mp4
provider: cuda
replicate_token: ''
selected_theme: Default
server_name: ''
server_port: 7861
server_share: false
use_os_temp_folder: false
video_quality: 14
