clear_output: true
fal_token: ''
force_cpu: false
huggingface_token: ''
last_source_folder: D:\.autodeep_temp\e47ab167a2f9e71294b838dcf095a5e4f4d011988da77ea02e6e8a36bbba4b65
last_target_folder: C:\Users\INdaHouse\Desktop\AutoDeep_Destino
max_threads: 4
memory_limit: 0
output_image_format: png
output_path: ''
output_show_video: true
output_template: '{file}_{time}'
output_video_codec: libx264
output_video_format: mp4
provider: cuda
replicate_token: ''
selected_theme: Default
server_name: ''
server_port: 9000
server_share: false
use_os_temp_folder: false
video_quality: 14
