#!/usr/bin/env python
"""Replace FLUX block in generate_intelligent with enhanced version supporting preserve_background and resolution."""

with open('roop/img_editor/img_editor_manager.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# New block (lines 826-861 old) -> replace with new block
new_block = [
    "        if engine in [\"flux\", \"flux_klein\", \"flux_schnell\"]:\n",
    "            print(\"[ImgEditor] === FLUX IMAGE EDIT ===\", flush=True)\n",
    "            print(f\"[ImgEditor] Prompt: {prompt[:100]}\", flush=True)\n",
    "            try:\n",
    "                from roop.img_editor.flux_edit_comfy_client import get_flux_edit_comfy_client\n",
    "                print(\"[ImgEditor] Import OK\", flush=True)\n",
    "\n",
    "                if self.flux_edit_client is None:\n",
    "                    self.flux_edit_client = get_flux_edit_comfy_client()\n",
    "                    print(\"[ImgEditor] FLUX Client creado\", flush=True)\n",
    "\n",
    "                # Determinar versión FLUX\n",
    "                flux_version = \"flux_klein\" if engine in [\"flux\", \"flux_klein\"] else \"flux_schnell\"\n",
    "                if flux_version == \"flux_schnell\":\n",
    "                    print(\"[WARN] FLUX.1-schnell usa GGUF T5 que es MUY LENTO (~20+ min). Se recomienda FLUX.2-klein.\")\n",
    "\n",
    "                # Detectar si se quiere preservar fondo/composición\n",
    "                prompt_lw = prompt.lower()\n",
    "                preserve_keywords = [\n",
    "                    'mantener fondo', 'conservar fondo', 'preservar fondo',\n",
    "                    'mantener composicion', 'conservar composicion', 'preservar composicion',\n",
    "                    'mantener composición', 'conservar composición', 'preservar composición',\n",
    "                    'mantener entorno', 'conservar entorno', 'preservar entorno',\n",
    "                    'keep background', 'maintain background', 'preserve background', 'background unchanged',\n",
    "                    'keep composition', 'maintain composition', 'preserve composition',\n",
    "                    'keep scene', 'maintain scene', 'preserve scene',\n",
    "                    'no cambies el fondo', 'do not change background',\n",
    "                    'manteniendo', 'conservando', 'preservando',  # gerundios\n",
    "                    'mantener', 'conservar', 'preservar'  # infinitivos\n",
    "                ]\n",
    "                preserve_background = any(kw in prompt_lw for kw in preserve_keywords)\n",
    "\n",
    "                # Calcular resolución objetivo desde ref_metadata\n",
    "                target_w, target_h = None, None\n",
    "                if ref_metadata and 'resolution_label' in ref_metadata:\n",
    "                    resolution = ref_metadata['resolution_label']\n",
    "                    try:\n",
    "                        max_side = int(resolution.replace('p', ''))\n",
    "                        w, h = image.size\n",
    "                        if w >= h:\n",
    "                            target_w = max_side\n",
    "                            target_h = int(h * (max_side / w))\n",
    "                        else:\n",
    "                            target_h = max_side\n",
    "                            target_w = int(w * (max_side / h))\n",
    "                        target_w = (target_w // 16) * 16\n",
    "                        target_h = (target_h // 16) * 16\n",
    "                        print(f\"[ImgEditor] Resolución objetivo: {target_w}x{target_h} (original {w}x{h})\")\n",
    "                    except:\n",
    "                        pass\n",
    "\n",
    "                # Determinar denoise: usar ref_metadata['denoise'] si existe, sino strength\n",
    "                denoise = strength\n",
    "                if ref_metadata:\n",
    "                    denoise = ref_metadata.get('denoise', denoise)\n",
    "\n",
    "                print(\"[ImgEditor] Cargando modelos FLUX...\", flush=True)\n",
    "                success, msg = self.flux_edit_client.load(\n",
    "                    progress_callback=progress_callback, flux_version=flux_version\n",
    "                )\n",
    "                print(f\"[ImgEditor] Load result: {success} - {msg}\", flush=True)\n",
    "                if not success:\n",
    "                    print(f\"[ImgEditor] ERROR cargando FLUX: {msg}\", flush=True)\n",
    "                    return None, f\"Error Motor FLUX: {msg}\"\n",
    "\n",
    "                print(\"[ImgEditor] Generando con FLUX...\", flush=True)\n",
    "                result_obj, msg = self.flux_edit_client.generate(\n",
    "                    image=image,\n",
    "                    prompt=prompt,\n",
    "                    num_inference_steps=num_inference_steps,\n",
    "                    guidance_scale=guidance_scale,\n",
    "                    seed=seed,\n",
    "                    denoise=denoise,\n",
    "                    preserve_background=preserve_background,\n",
    "                    target_width=target_w,\n",
    "                    target_height=target_h,\n",
    "                    flux_version=flux_version\n",
    "                )\n",
    "                print(f\"[ImgEditor] Generate result: {result_obj is not None} - {msg}\", flush=True)\n",
    "\n",
    "                if result_obj and result_obj.image:\n",
    "                    return result_obj.image, f\"FLUX Edit completada ({result_obj.time_taken:.1f}s)\"\n",
    "                return None, f\"Fallo en FLUX Edit: {msg}\"\n",
    "            except Exception as e:\n",
    "                print(f\"[ImgEditor] ERROR en motor FLUX: {e}\", flush=True)\n",
    "                import traceback\n",
    "                print(traceback.format_exc(), flush=True)\n",
    "                return None, f\"Error Motor FLUX: {str(e)}\"\n",
]

# Original block lines 826-861 inclusive (0-index 825-860)
start_idx = 825
end_idx = 861  # slice end exclusive, so we replace indices 825..860
new_lines = lines[:start_idx] + new_block + lines[end_idx:]

with open('roop/img_editor/img_editor_manager.py', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print("Flux block replaced successfully.")
